# This file contains printer configuration values, one per line.
# Comment lines beginning with # or ; will be ignored.
# For more convenient navigation, settings are grouped into categories
# with headings proceeded by two hash characters (##) and followed
# by a colon. You can search for a section heading by name to find the relevant
# settings.

## Table of Contents:
# - Metadata
# - Temperatures
# - Bed adhesion
# - Layer height
# - Part strength
# - Speeds
# - Supports
# - Infill
# - Part surface
# - Retraction
# - Perimeter tweaks
# - Overhangs and bridging
# - Part cooling
# - Extrusion and flow
# - GCode scripts
# - GCode output format
# - Multi-material printing
# - Nozzle purge
# - Slicing strategies
# - Filament properties
# - Extruder design
# - Acceleration
# - Printer geometry
# - Printer physical limits
# - Miscellaneous

## Metadata:
printer_settings_id = Flashforge Adventurer 5M 0.4 Nozzle
printer_variant = 0.4
print_settings_id = 0.20mm Standard @Flashforge AD5M 0.4 Nozzle
printer_model = Flashforge Adventurer 5M
printer_notes = 

## Temperatures:
temperature = 220
bed_temperature = 55
first_layer_temperature = 220
first_layer_bed_temperature = 55
standby_temperature_delta = -5

## Bed adhesion:
skirts = 0
skirt_distance = 2
skirt_height = 1
brim_type = no_brim
brim_width = 5
raft_layers = 0
raft_contact_distance = 0.1
raft_expansion = 1.5
raft_first_layer_density = 90%
raft_first_layer_expansion = 2
draft_shield = disabled
first_layer_height = 0.2

## Layer height:
layer_height = 0.2

## Part strength:
perimeters = 2
bottom_solid_layers = 3
top_solid_layers = 5

## Speeds:
perimeter_speed = 300
small_perimeter_speed = 50%
external_perimeter_speed = 200
infill_speed = 270
solid_infill_speed = 250
top_solid_infill_speed = 200
support_material_speed = 150
support_material_interface_speed = 80
bridge_speed = 25
gap_fill_speed = 200
ironing_speed = 15
first_layer_speed = 50
retract_speed = 35
travel_speed = 500
travel_speed_z = 0

## Supports:
support_material_bottom_contact_distance = 0.18
support_material_bottom_interface_layers = 2
support_material_interface_layers = 2
support_material_threshold = 30
support_material_xy_spacing = 0.3
interface_shells = 0

## Infill:
fill_density = 15%
fill_pattern = crosshatch

## Part surface:
ironing_spacing = 0.1
fuzzy_skin = none
fuzzy_skin_thickness = 0.2

## Retraction:
wipe = 1
retract_before_wipe = 100%
retract_length = 0.8
retract_length_toolchange = 2
retract_lift = 0.4
retract_lift_above = 0
retract_lift_below = 0
retract_restart_extra = 0
retract_restart_extra_toolchange = 0

## Perimeter tweaks:
wall_distribution_count = 1
wall_transition_angle = 10
wall_transition_length = 100%
wall_transition_filter_deviation = 25%
seam_position = aligned

## Overhangs and bridging:
bridge_angle = 0
thick_bridges = 0

## Part cooling:
full_fan_speed_layer = 0

## Extrusion and flow:
extrusion_width = 0.42
external_perimeter_extrusion_width = 0.42
infill_extrusion_width = 0.45
perimeter_extrusion_width = 0.45
solid_infill_extrusion_width = 0.42
support_material_extrusion_width = 0.42
top_infill_extrusion_width = 0.42

## GCode scripts:
start_filament_gcode = "; Filament gcode\n"
start_gcode = M190 S[bed_temperature_initial_layer_single]\nM104 S[nozzle_temperature_initial_layer]\nG90\nM83\nG1 Z5 F6000\nG1 E-0.2 F800\nG1 X110 Y-110 F6000\nG1 E2 F800\nG1 Y-110 X55 Z0.25 F4800\nG1 X-55 E8 F2400\nG1 Y-109.6 F2400\nG1 X55 E5 F2400\nG1 Y-110 X55 Z0.45 F4800\nG1 X-55 E8 F2400\nG1 Y-109.6 F2400\nG1 X55 E5 F2400\nG92 E0
end_gcode = G1 E-3 F3600\nG0 X50 Y50 F30000\nM104 S0 ; turn off temperature
before_layer_gcode = ;BEFORE_LAYER_CHANGE\n;[layer_z]
layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
end_filament_gcode = "; filament end gcode\n"
toolchange_gcode = 
pause_print_gcode = M25
template_custom_gcode = 

## GCode output format:
gcode_flavor = klipper
use_firmware_retraction = 0
use_relative_e_distances = 1

## Multi-material printing:
mmu_segmented_region_interlocking_depth = 0
mmu_segmented_region_max_width = 0
ooze_prevention = 0

## Nozzle purge:
wipe_tower_no_sparse_layers = 0
wipe_tower_rotation_angle = 0
wipe_tower_x = 165
wipe_tower_y = 250
filament_minimal_purge_on_wipe_tower = 15

## Slicing strategies:
resolution = 0.012
min_feature_size = 25%
min_bead_width = 85%
slice_closing_radius = 0.049
slicing_mode = regular

## Filament properties:
filament_density = 1.24
filament_diameter = 1.75

## Extruder design:
single_extruder_multi_material = 0
nozzle_diameter = 0.4
extruder_offset = 0x0

## Acceleration:
default_acceleration = 10000
travel_acceleration = 10000

## Printer geometry:
bed_shape = -110x-110,110x-110,110x110,-110x110
bed_custom_model = 
bed_custom_texture = 

## Printer physical limits:
printer_technology = FFF
machine_max_acceleration_e = 5000,5000
machine_max_acceleration_extruding = 20000,20000
machine_max_acceleration_retracting = 5000,5000
machine_max_acceleration_travel = 20000,20000
machine_max_acceleration_x = 20000,20000
machine_max_acceleration_y = 20000,20000
machine_max_acceleration_z = 500,500
machine_max_jerk_e = 2.5,2.5
machine_max_jerk_x = 9,9
machine_max_jerk_y = 9,9
machine_max_jerk_z = 3,3
machine_min_extruding_rate = 0,0
machine_min_travel_rate = 0,0
max_fan_speed = 100
min_fan_speed = 100
max_layer_height = 0.28
min_layer_height = 0.08
max_print_height = 220

## Miscellaneous:
elefant_foot_compensation = 0.15
silent_mode = 0
post_process = 
