[METADATA] # This is a special key, not a library
published_at = '2025-02-24'

[BOSL]
full_name = 'Belfry OpenSCAD Library'
[[BOSL.versions]]
version = '1.0.3'
archive = 'https://github.com/revarbat/BOSL/archive/refs/tags/v1.0.3.zip'
subdir = 'BOSL-1.0.3'

[Round-Anything]
full_name = 'Round Anything'
[[Round-Anything.versions]]
version = '1.0.4'
archive = 'https://github.com/Irev-Dev/Round-Anything/archive/refs/tags/1.0.4.zip'
subdir = 'Round-Anything-1.0.4'

[dotSCAD]
full_name = 'dotSCAD'
[[dotSCAD.versions]]
version = '3.3'
archive = 'https://github.com/JustinSDK/dotSCAD/archive/refs/tags/v3.3.zip'
subdir = 'dotSCAD-3.3/src'

[constructive]
full_name = 'Constructive Library'
[[constructive.versions]]
version = '2023.02.18'
archive = 'https://github.com/solidboredom/constructive/raw/e7352ecfa6998fae55890162c8bbc84edf30b8d6/kickstart.zip'
subdir = 'cad_kickstart'
